CREATE TABLE [dbo].[SPECIMEN]
(
	[SPECIMEN_ID] INT NOT NULL PRIMARY KEY, 
    [SPECIMEN_CODE] NVARCHAR(10) NULL, 
    [SPECIMEN_NAME] NVARCHAR(128) NULL, 
    [SPECIMEN_VOLUMEUNIT] NVARCHAR(10) NULL
)
