CREATE TABLE [dbo].[PATIENT]
(
	[PATIENT_ID] INT NOT NULL PRIMARY KEY, 
    [PATIENT_MRN] INT NULL, 
    [PATIENT_FIRSTNAME] NVARCHAR(128) NULL, 
    [PATIENT_LASTNAME] NVARCHAR(128) NULL, 
    [PATIENT_GENDER] NVARCHAR(10) NULL
)
